### ISSUE TITLE
problems with 

### ISSUE THREAD

**Issue by ser2131604** [alexandretok/ionic2-rating#3] opened 2017-11-02 01:39 UTC
Im getting this runtime error. pls help
Runtime Error
Uncaught (in promise): Error: Template parse errors: Can't bind to 'numStars' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'numStars' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-rating [ERROR ->][numStars]="5" [readOnly]="false" [value]="3.2" "): ng:///ListMasterPageModule/ListMasterPage.html@10:6 Can't bind to 'readOnly' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'readOnly' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-rating [numStars]="5" [ERROR ->][readOnly]="false" [value]="3.2" (clicked)="starClicked($event)"> "): ng:///ListMasterPageModule/ListMasterPage.html@11:6 Can't bind to 'value' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'value' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" [numStars]="5" [readOnly]="false" [ERROR ->][value]="3.2" (clicked)="starClicked($event)"> </ion-rating> "): ng:///ListMasterPageModule/ListMasterPage.html@12:6 'ion-rating' is not a known element: 1. If 'ion-rating' is an Angular component, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" <ion-content> [ERROR ->]<ion-rating [numStars]="5" [readOnly]="false" "): ng:///ListMasterPageModule/ListMasterPage.html@9:4 Error: Template parse errors: Can't bind to 'numStars' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'numStars' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-rating [ERROR ->][numStars]="5" [readOnly]="false" [value]="3.2" "): ng:///ListMasterPageModule/ListMasterPage.html@10:6 Can't bind to 'readOnly' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'readOnly' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-rating [numStars]="5" [ERROR ->][readOnly]="false" [value]="3.2" (clicked)="starClicked($event)"> "): ng:///ListMasterPageModule/ListMasterPage.html@11:6 Can't bind to 'value' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'value' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" [numStars]="5" [readOnly]="false" [ERROR ->][value]="3.2" (clicked)="starClicked($event)"> </ion-rating> "): ng:///ListMasterPageModule/ListMasterPage.html@12:6 'ion-rating' is not a known element: 1. If 'ion-rating' is an Angular component, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" <ion-content> [ERROR ->]<ion-rating [numStars]="5" [readOnly]="false" "): ng:///ListMasterPageModule/ListMasterPage.html@9:4 at syntaxError (http://localhost:8100/build/vendor.js:82632:34) at TemplateParser.parse (http://localhost:8100/build/vendor.js:93875:19) at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:108071:39) at http://localhost:8100/build/vendor.js:107990:62 at Set.forEach (<anonymous>) at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:107990:19) at http://localhost:8100/build/vendor.js:107877:19 at Object.then (http://localhost:8100/build/vendor.js:82621:143) at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:107876:26) at JitCompiler.compileModuleAsync (http://localhost:8100/build/vendor.js:107805:37)Runtime Error
Uncaught (in promise): Error: Template parse errors: Can't bind to 'numStars' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'numStars' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-rating [ERROR ->][numStars]="5" [readOnly]="false" [value]="3.2" "): ng:///ListMasterPageModule/ListMasterPage.html@10:6 Can't bind to 'readOnly' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'readOnly' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-rating [numStars]="5" [ERROR ->][readOnly]="false" [value]="3.2" (clicked)="starClicked($event)"> "): ng:///ListMasterPageModule/ListMasterPage.html@11:6 Can't bind to 'value' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'value' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" [numStars]="5" [readOnly]="false" [ERROR ->][value]="3.2" (clicked)="starClicked($event)"> </ion-rating> "): ng:///ListMasterPageModule/ListMasterPage.html@12:6 'ion-rating' is not a known element: 1. If 'ion-rating' is an Angular component, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" <ion-content> [ERROR ->]<ion-rating [numStars]="5" [readOnly]="false" "): ng:///ListMasterPageModule/ListMasterPage.html@9:4 Error: Template parse errors: Can't bind to 'numStars' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'numStars' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-rating [ERROR ->][numStars]="5" [readOnly]="false" [value]="3.2" "): ng:///ListMasterPageModule/ListMasterPage.html@10:6 Can't bind to 'readOnly' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'readOnly' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-rating [numStars]="5" [ERROR ->][readOnly]="false" [value]="3.2" (clicked)="starClicked($event)"> "): ng:///ListMasterPageModule/ListMasterPage.html@11:6 Can't bind to 'value' since it isn't a known property of 'ion-rating'. 1. If 'ion-rating' is an Angular component and it has 'value' input, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" [numStars]="5" [readOnly]="false" [ERROR ->][value]="3.2" (clicked)="starClicked($event)"> </ion-rating> "): ng:///ListMasterPageModule/ListMasterPage.html@12:6 'ion-rating' is not a known element: 1. If 'ion-rating' is an Angular component, then verify that it is part of this module. 2. If 'ion-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" <ion-content> [ERROR ->]<ion-rating [numStars]="5" [readOnly]="false" "): ng:///ListMasterPageModule/ListMasterPage.html@9:4 at syntaxError (http://localhost:8100/build/vendor.js:82632:34) at TemplateParser.parse (http://localhost:8100/build/vendor.js:93875:19) at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:108071:39) at http://localhost:8100/build/vendor.js:107990:62 at Set.forEach (<anonymous>) at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:107990:19) at http://localhost:8100/build/vendor.js:107877:19 at Object.then (http://localhost:8100/build/vendor.js:82621:143) at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:107876:26) at JitCompiler.compileModuleAsync (http://localhost:8100/build/vendor.js:107805:37)

**Comment by alexandretok** [comment] 2017-11-03 01:45
Duplicate of #2

**Closed as completed** 2017-12-13 20:18 UTC
